### ISSUE TITLE
issue with .deb install > 0.93

### ISSUE THREAD

**Issue by Pada0** [TriliumNext/trilium#5824]
### Description

Hi there,

0.92.x and 0.93 are ok
But with 0.94.1 and 0.95 I have this error message

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /usr/lib/trilium/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2569)
    at Module._extensions..node (node:internal/modules/cjs/loader:1930:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2796)
    at Module.load (node:internal/modules/cjs/loader:1472:32)
    at Module._load (node:internal/modules/cjs/loader:1289:12)
    at c._load (node:electron/js2c/node_init:2:17950)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:242:24)
    at Module.require (node:internal/modules/cjs/loader:1494:12)
    at require (node:internal/modules/helpers:135:16)
[27335:0621/152627.255461:ERROR:components/viz/service/main/viz_main_impl.cc:183] Exiting GPU process due to errors during initialization

### TriliumNext Version

0.94.1

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

debian 12

### Error logs

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /usr/lib/trilium/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2569)
    at Module._extensions..node (node:internal/modules/cjs/loader:1930:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2796)
    at Module.load (node:internal/modules/cjs/loader:1472:32)
    at Module._load (node:internal/modules/cjs/loader:1289:12)
    at c._load (node:electron/js2c/node_init:2:17950)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:242:24)
    at Module.require (node:internal/modules/cjs/loader:1494:12)
    at require (node:internal/modules/helpers:135:16)
[27335:0621/152627.255461:ERROR:components/viz/service/main/viz_main_impl.cc:183] Exiting GPU process due to errors during initialization

**Comment by Pada0** [comment]
Thanks ! The nightly build works 👍

**Comment by LiamFry** [comment]
I know this issue is closed, but ...
I run my own server and prefer the locally-installed client for access. Needless to say (but saying), I have the _exact_ same issue; I'm running Debian 12 with glibc 2.36
I don't do *Snap* or *FlatPak* for deeply religious reasons, so *FlatPak* is a "no-go" for me.
(For now, I have no choice but to live with web access.)

And here's my question: Why was I able to successfully upgrade the server to 0.95.0, i.e. no `glibc` 2.38 dependency errors? Does the server not have the same `better-sqlite` and `glibc` 2.38 dependencies?

**Comment by eliandoran** [comment]
@LiamFry , the issue you're having should be fixed in https://github.com/TriliumNext/Trilium/commit/1ac086b88e404cbd4f2a391baf5f7de1659a47db.

Please test on the [latest nightly](https://github.com/TriliumNext/Trilium/releases/nightly) and let me know. :)

**Comment by linull24** [comment]
![Image](https://github.com/user-attachments/assets/dfbbe47a-4ffe-4373-9788-59817aa4c892)

Using the latest release flatpak version still failed.
I'm running on ArchlinuxARM, so I guess there is few possibility of GLIBC version issue.

**Comment by eliandoran** [comment]
@linull24 , I suppose you're having the same error as this one: https://github.com/TriliumNext/Trilium/issues/5810

**Comment by linull24** [comment]
> [@linull24](https://github.com/linull24) , I suppose you're having the same error as this one: [#5810](https://github.com/TriliumNext/Trilium/issues/5810)

Yes,and I tried: RPM package(using AUR),flatpak,and native deb on unstable.ALL FAILED.

**Comment by eliandoran** [comment]
@linull24 , I'll try to have a look at it in the upcoming days but it's rather difficult without Linux ARM hardware on my side.

**Comment by aaronsantiago** [comment]
For the record I'm having the same issue on the latest stable and the nightly thru flatpak. I'm on Fedora ARM (asahi linux on an m1 air).

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /app/lib/com.triliumnext.notes/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2617)
    at Module._extensions..node (node:internal/modules/cjs/loader:1930:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2844)
    at Module.load (node:internal/modules/cjs/loader:1472:32)
    at Module._load (node:internal/modules/cjs/loader:1289:12)
    at c._load (node:electron/js2c/node_init:2:18013)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:242:24)
    at Module.require (node:internal/modules/cjs/loader:1494:12)
    at require (node:internal/modules/helpers:135:16)
```

My glibc version:
```
$ ldd --version
ldd (GNU libc) 2.41
```
