### ISSUE TITLE
readOnly Editor Doesn't Appear

### ISSUE THREAD

**Issue by TheAdamsFamily25** [TriliumNext/Trilium#8091]
### Description

Hello,

Noticed a small bug in that the editor doesn't appear (on a regular basis) when I click the pencil to edit note. I'm able to type and add text however the toolbar doesn't show up. Example below after enabling edit note.

<img width="1052" height="86" alt="Image" src="https://github.com/user-attachments/assets/ff5e6aa0-9865-4e83-9086-d4277c20c274" />

Many thanks,
Adam

### TriliumNext Version

Latest (Docker Compose)

### What operating system are you using?

Other (specify below)

### What is your setup?

Local + server sync

### Operating System Version

Server Sync setup. Reproducable on both Firefox and Mac OS apps.

**Comment by eliandoran** [comment]
Should be fixed in the upcoming version, let me know if it's still the case.
Can already be tested on the latest nightly.

**Comment by Talk2Giuseppe** [comment]
This bug still persists in 0.103.0 (database: 238, sync protocol: 39).

Perhaps adding a refresh button to the UI to give us a better UX would be helpful until this bug is resolved.  Meanwhile, the suggested solutions to bring back the editing bar don't seem to work.  That pretty much renders this application useless until it's resolved.

I'm looking forward to giving this a better look when it's ready.

Thanks!

**Comment by eliandoran** [comment]
@Talk2Giuseppe , interesting.

There are two work-arounds:

* Switch to the [new layout](https://docs.triliumnotes.org/user-guide/concepts/ui/new-layout), I don't see the issue occurring in there.
* There are two ways to refresh the app: press <kbd>F5</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> or Global Menu -> Advanced -> Reload frontend.

**Comment by Talk2Giuseppe** [comment]
> There are two work-arounds:
> 
> * Switch to the [new layout](https://docs.triliumnotes.org/user-guide/concepts/ui/new-layout), I don't see the issue occurring in there.
> * There are two ways to refresh the app: press F5 or Ctrl+Shift+R or Global Menu -> Advanced -> Reload frontend.

Thank you for the reply.  None of this is helpful.  I am still absolutely lost in finding what you mentioned and the F5 doesn't do anything but refresh the page.  Changing the note type also does nothing to bring back the editing bar.

Perhaps it has something to do with it being a docker install?

EDIT: I just remembered that I tried to install an addon to create collapseable sections.  Perhaps I borked the install.  I am going to blow on the container and directories and rebuild the container from stratch and see if that brings this functionality to life.

**Comment by eliandoran** [comment]
@Talk2Giuseppe , note type has nothing to do with this issue.

You are most likely using the old layout, where the issue occurs. Switching to new layout in Options -> Appearance -> New layout should fix your issue.

You can also disable temporarily the automatic read-only by going to Options -> Text Notes -> Automatic read-only size and put it to a large value (e.g. 999999).

Not sure if starting from scratch will help here since it's indeed an bug.

The fix will land in the next release, but you can test the tomorrow's [nightly release](https://docs.triliumnotes.org/user-guide/advanced-usage/nightly-release).

**Comment by Talk2Giuseppe** [comment]
Ok, a wipe and reinstall didn't seem to fix it.  Nor did any of the recommendations offered help.

Although, the note I am working on is a sub note and that is where I am encountering this bug.  But if I go to the folder above it, the editing bar will be seen.  I suspect I can do my editing in the parent folder and when done, copy/paste my edits into my actual document until the fix is implemented.

<img width="1916" height="919" alt="Image" src="https://github.com/user-attachments/assets/5aebb203-1db5-4b94-9230-8fd39e89c57d" />

**Comment by eliandoran** [comment]
@Talk2Giuseppe , that is not a bug. The editing toolbar is only for Text notes whereas the Code notes don't have a formatting toolbar since there is nothing to format in a code note. Are you looking for a specific option?

**Comment by Talk2Giuseppe** [comment]
Well, then there is a different bug.  Because switching back to text doesn't offer the editing tools.  Either way, there's a bug.

**Comment by eliandoran** [comment]
@Talk2Giuseppe , can you record a video of the bug? I'm trying to understand if I fixed it or not.
